services:
  ollama:
    image: ollama/ollama:0.6.5-rocm
    container_name: ollama
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    ports:
      - 11434:11434
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
    volumes:
      - ./data/ollama:/root/.ollama
      - ./data/models:/models

  open-webui:
    image: ghcr.io/open-webui/open-webui:git-aaefba2
    container_name: open-webui
    depends_on:
      - ollama
    ports:
      - 80:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    volumes:
      - ./data/open-webui:/app/backend/data
