services:
  ollama:
    image: ollama/ollama:0.6.6
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
      - ./data/models:/models

  open-webui:
    image: ghcr.io/open-webui/open-webui:git-4ee5dd5
    container_name: open-webui
    depends_on:
      - ollama
    ports:
      - 80:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    volumes:
      - ./data/open-webui:/app/backend/data
